export const ErrorCode = {
  INVALID_REQUEST: 'INVALID_REQUEST',

  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  DATABASE_ERROR: 'DATABASE_ERROR',
  INVALID_RESPONSE: 'INVALID_RESPONSE',

  AI_LOCK_ACTIVE: 'AI_LOCK_ACTIVE',
  AI_LOCK_REQUEST_FAILED: 'AI_LOCK_REQUEST_FAILED',
  AI_TIMEOUT: 'AI_TIMEOUT',
  AI_RATE_LIMIT: 'AI_RATE_LIMIT',
  AI_GENERATION_FAILED: 'AI_GENERATION_FAILED',
  AI_BAD_RESPONSE: 'AI_BAD_RESPONSE',
  AI_UNAVAILABLE: 'AI_UNAVAILABLE',
  AI_INVALID_RESPONSE_FORMAT: 'AI_INVALID_RESPONSE_FORMAT',
  AI_EMPTY_RESPONSE: 'AI_EMPTY_RESPONSE',
  AI_REQUEST_LIMIT: 'AI_REQUEST_LIMIT',
  AI_REQUEST_ERROR: 'AI_REQUEST_ERROR',

  NETWORK_ERROR: 'NETWORK_ERROR',

  UNKNOWN: 'UNKNOWN',

  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export const AI_GENERATION_CANCEL_CODES = {
  client_disconnect: 'AI_GENERATION_CLIENT_DISCONNECT',
  timeout: 'AI_GENERATION_TIMEOUT',
  server_shutdown: 'AI_GENERATION_SERVER_SHUTDOWN',
};

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
