import { ErrorCode } from "./code";

export const ErrorHttpStatus: Record<ErrorCode, number> = {
  INVALID_REQUEST: 400,

  AUTHORIZATION_ERROR: 401,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,

  DATABASE_ERROR: 500,
  INVALID_RESPONSE: 422,

  AI_TIMEOUT: 504,
  AI_RATE_LIMIT: 429,
  AI_GENERATION_FAILED: 502,
  AI_BAD_RESPONSE: 422,
  AI_UNAVAILABLE: 503,
  AI_INVALID_RESPONSE_FORMAT: 422,
  AI_EMPTY_RESPONSE: 422,
  AI_LOCK_REQUEST: 500,

  NETWORK_ERROR: 503,

  UNKNOWN: 500,

  INTERNAL_SERVER_ERROR: 500,
};
